const List<String> kLanguages = <String>[
  'Afrikaans', 'Albanian', 'Amharic', 'Arabic',
  'Moroccan Arabic (Darija)', 'Armenian', 'Azerbaijani', 'Basque',
  'Belarusian', 'Bengali', 'Bosnian', 'Bulgarian', 'Catalan', 'Cebuano',
  'Chinese (Simplified)', 'Chinese (Traditional)', 'Corsican', 'Croatian',
  'Czech', 'Danish', 'Dutch', 'Dutch (Flemish)', 'English (US)',
  'English (UK)', 'Esperanto', 'Estonian', 'Finnish', 'French', 'Frisian',
  'Galician', 'Georgian', 'German', 'Greek', 'Gujarati', 'Haitian Creole',
  'Hausa', 'Hawaiian', 'Hebrew', 'Hindi', 'Hmong', 'Hungarian', 'Icelandic',
  'Igbo', 'Indonesian', 'Irish', 'Italian', 'Japanese', 'Javanese', 'Kannada',
  'Kazakh', 'Khmer', 'Kinyarwanda', 'Korean', 'Kurdish', 'Kyrgyz', 'Lao',
  'Latin', 'Latvian', 'Lithuanian', 'Luxembourgish', 'Macedonian', 'Malagasy',
  'Malay', 'Malayalam', 'Maltese', 'Maori', 'Marathi', 'Mongolian',
  'Myanmar (Burmese)', 'Nepali', 'Norwegian', 'Nyanja (Chichewa)',
  'Odia (Oriya)', 'Pashto', 'Persian', 'Polish', 'Portuguese (Portugal)',
  'Portuguese (Brazil)', 'Punjabi', 'Romanian', 'Russian', 'Samoan',
  'Scots Gaelic', 'Serbian', 'Sesotho', 'Shona', 'Sindhi',
  'Sinhala (Sinhalese)', 'Slovak', 'Slovenian', 'Somali', 'Spanish',
  'Sundanese', 'Swahili', 'Swedish', 'Tagalog (Filipino)', 'Tajik', 'Tamil',
  'Tatar', 'Telugu', 'Thai', 'Turkish', 'Turkmen', 'Ukrainian', 'Urdu',
  'Uyghur', 'Uzbek', 'Vietnamese', 'Welsh', 'Xhosa', 'Yiddish', 'Yoruba',
  'Zulu',
];

const List<String> kVoiceProfiles = <String>[
  'Auto (installed local pack)',
  'Flemish - Nathalie medium',
  'Flemish - Nathalie x_low',
  'Text only (TTS disabled)',
];
